%%
[~,td_co] = getTDidx(trial_data,'task','CO','result','R');
[~,td_cst] = getTDidx(trial_data,'task','CST','result','R');
% td_co = trimTD(td_co,{'idx_goCueTime',-400},{'idx_endTime',0});
for trialnum=1:length(td_cst)
%     trialnum = 7;
    trial = td_cst(trialnum);
    h=figure;
    h_x_pos = plot(trial.left_eye_pos(:,1));
    hold on
    h_y_pos = plot(trial.left_eye_pos(:,2));
    h_pupil = plot(trial.left_pupil);
    

    y_limits = get(gca,'ylim');
    plot([1;1]*trial.idx_ctHoldTime,y_limits,'--k','linewidth',2)
    plot([1;1]*trial.idx_goCueTime,y_limits,'--k','linewidth',2)
    plot([1;1]*trial.idx_rewardTime,y_limits,'--k','linewidth',2)
    plot([0 1000],[1 1]*y_limits(1)*0.5,'-k','linewidth',4)
    text(500,y_limits(1)*0.5-1,'1 second','FontSize',10)


    title(sprintf('Direction %.2f, Magnitude %.2f',trial.tgtDir,trial.tgtMag))
    legend([h_x_pos,h_y_pos,h_pupil],'Eye position X', 'Eye position Y', 'Pupil diameter')

    set(gca, ...
        'box','off', ...
        'tickdir','out', ...
        'xtick',[ ...
            trial.idx_ctHoldTime, ...
            trial.idx_goCueTime, ...
            trial.idx_rewardTime ...
            ],...
        'xticklabel',[ ...
            repmat({'Center Hold'},size(trial.idx_ctHoldTime)), ...
            repmat({'Go Cue'},size(trial.idx_goCueTime)), ...
            repmat({'Reward'},size(trial.idx_rewardTime)), ...
            ]...
        )
    
    waitfor(h)
end